### ISSUE TITLE
Track Connectors usage at the core

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js-tracking#19]
### What should we do?

We want to be able to track Connectors across both Web and Desktop Modeler:

As per [the alignment I had with Bastian (PM of Connectors)](https://docs.google.com/document/d/1lD0rvFL9s7ogE5u5nLkheZNPiwiYt5uiaKEL2CHEBr4/edit?usp=sharing) we should focus with the first iteration on these three main goals:

1. All the events are tracked in the same way for both modelers and we can also identify the source of the event. Ideally at some point we can also do that in SM for customers that opt-in **=> will be achieved when integrated in web modeler**

3. When a user is using create and append anything, we want to know how many users choose one connector from the list and which one; identify by id, regardless if OOTB or custom
Make a difference between: create from palette, append from context pad, wrench-change from context pad **=> https://github.com/camunda/camunda-modeler/issues/3627**

4. When a user is using select template to apply a Connector, and also when the use it to unlink, remove or update **=> https://github.com/bpmn-io/bpmn-js-tracking/issues/28**

### Why should we do it?

to better understand how our users are using Connectors.

**Comment by smbea** [comment]
> Regarding 1 and 2

1 is being implemented already to achieve https://github.com/bpmn-io/internal-docs/issues/546. Tracking of popup menu entries (2) has been implemented. The id sent is the entry id, which for connectors would be `replace.<connector-id>`. With the integration, we will clean and filter the events according to our needs ([see discussion](https://github.com/bpmn-io/internal-docs/issues/746#issuecomment-1514731199)). We should make sure connectors ids are sent to Mixpanel in an easy-to-digest way.

> When a user is using select template to apply a Connector, and also when the use it to unlink, remove or update

We currently don't have a way to hook into this without listening to DOM interaction. We could follow a similar structure as we did for https://github.com/bpmn-io/diagram-js/issues/771

**Comment by smbea** [comment]
Regarding 1, and my comment above:
> 1 is being implemented already to achieve https://github.com/bpmn-io/internal-docs/issues/546. Tracking of popup menu entries (2) has been implemented. The id sent is the entry id, which for connectors would be replace.<connector-id>. With the integration, we will clean and filter the events according to our needs (https://github.com/bpmn-io/internal-docs/issues/746#issuecomment-1514731199). We should make sure connectors ids are sent to Mixpanel in an easy-to-digest way.

I mentioned we could add 1) in our [Mixpanel integration](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/user-journey-statistics/event-handlers/ModelingEventHandler.js#L80), in the same way we do it for[ filtering diagram elements](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/user-journey-statistics/event-handlers/ModelingEventHandler.js#L80): interpret the popup menu entries with id "replace/append.template-<template-id>" (added with crceate-append anything) as `templateId: <template-id>`. I believe this would follow our current strategy. Wdyt @nikku?

The alternative would be manually adding that in the core tracking.

**Comment by nikku** [comment]
> Interpret the popup menu entries with id "replace/append.template-" (added with crceate-append anything) as templateId: <template-id>. I believe this would follow our current strategy. Wdyt @nikku?

I think that is a reasonable strategy. It should work good enough for us.

**Comment by smbea** [comment]
I think we can close this issue. The missing piece is "All the events are tracked in the same way for both modelers". The infrastructure for this is in place, the rest will be implemented via the [web modeler tracking integration issue](https://github.com/camunda/web-modeler/issues/4577)
